# Generated by Django 3.1.1 on 2021-03-21 14:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Blog title', max_length=50)),
                ('full_news', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Here you acn write full news')),
                ('image', models.ImageField(default='default.jpg', upload_to='static/images/blog')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
