# Generated by Django 3.1.1 on 2021-01-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_news',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog_news',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='static/images/blog'),
        ),
    ]
