# Generated by Django 3.1.1 on 2021-01-25 15:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210125_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_news',
            name='full_news',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Here you can write your full news', verbose_name='Here you acn write full news'),
            preserve_default=False,
        ),
    ]
