# Generated by Django 3.1.1 on 2021-01-27 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_blog_news_full_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_news',
            name='author',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Author'),
            preserve_default=False,
        ),
    ]
