# Generated by Django 3.1.1 on 2021-01-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210127_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_news',
            name='author',
        ),
    ]
