# Generated by Django 3.1.1 on 2021-03-19 14:58

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('discount_price', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('H', 'House'), ('A', 'Apartment'), ('L', 'Land')], default='Error fetching category', max_length=2)),
                ('label', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='Active', max_length=2)),
                ('sold_or_rent', models.CharField(choices=[('sold', 'SOLD'), ('rent', 'RENT')], default='SOLD', max_length=4)),
                ('picture_count', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('owner_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(default='+977 9845900495', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9779812345678'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('location', models.CharField(choices=[('K', 'Kathmandu'), ('L', 'Lalitpur'), ('L', 'Bhaktapur'), ('C', 'Chitwan')], default='Kathmandu', max_length=2)),
                ('map', models.CharField(blank=True, max_length=150, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='static/images')),
                ('imageitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jaggasale.item')),
            ],
        ),
    ]
