# Generated by Django 3.1.1 on 2021-03-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='floors',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
