# Generated by Django 3.1.1 on 2020-10-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'House'), ('A', 'Apartment'), ('L', 'Land')], default='SOME STRING', max_length=2),
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('A', 'Active'), ('S', 'Sold')], default='SOME STRING', max_length=2),
        ),
    ]
