# Generated by Django 3.1.1 on 2020-10-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0002_auto_20201008_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='defeult.jpg', upload_to='static/images'),
        ),
    ]
