# Generated by Django 3.1.1 on 2021-03-19 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0002_auto_20210319_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('K', 'Kathmandu'), ('L', 'Lalitpur'), ('L', 'Bhaktapur'), ('C', 'Chitwan')], max_length=2),
        ),
    ]
