# Generated by Django 3.1.1 on 2020-10-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0003_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rooms',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
