# Generated by Django 3.1.1 on 2021-03-20 02:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0003_auto_20210319_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='phone_number',
            field=models.CharField(default='+977 ', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9779812345678'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
