# Generated by Django 3.1.1 on 2020-10-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0004_item_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='lable_color',
            field=models.CharField(choices=[('RED', 'badge-danger'), ('GREEN', 'badge-success')], default='GREEN', max_length=20),
        ),
    ]
