# Generated by Django 3.1.1 on 2021-03-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0004_auto_20210321_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
