# Generated by Django 3.1.1 on 2020-10-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0005_item_lable_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='lable_color',
            field=models.CharField(choices=[('badge-danger', 'badge-danger'), ('GREEN', 'badge-success')], default='GREEN', max_length=20),
        ),
    ]
