# Generated by Django 3.1.1 on 2021-03-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0005_auto_20210320_0248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='images',
        ),
    ]
