# Generated by Django 3.1.1 on 2021-03-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0006_item_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'House'), ('A', 'Apartment'), ('L', 'Land')], default='House', max_length=2),
        ),
    ]
