# Generated by Django 3.1.1 on 2020-10-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0006_auto_20201008_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='lable_color',
        ),
        migrations.AddField(
            model_name='item',
            name='picture_count',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
