# Generated by Django 3.1.1 on 2020-10-08 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jaggasale', '0007_auto_20201008_0752'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='PropertiesForRent',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='PropertiesForSold',
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('A', 'Active'), ('R', 'Rent')], default='SOME STRING', max_length=2),
        ),
    ]
