# Generated by Django 3.1.1 on 2021-03-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0007_auto_20210320_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='have_parking',
            field=models.BooleanField(default=False, verbose_name='Parking'),
        ),
    ]
