# Generated by Django 3.1.1 on 2021-03-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0007_auto_20210328_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'House'), ('A', 'Apartment'), ('L', 'Land')], max_length=2),
        ),
    ]
