# Generated by Django 3.1.1 on 2020-10-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0008_auto_20201008_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertiesforsold',
            name='bathroom',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertiesforsold',
            name='category',
            field=models.CharField(choices=[('H', 'House'), ('A', 'Apartment'), ('L', 'Land')], default='SOME STRING', max_length=2),
        ),
        migrations.AddField(
            model_name='propertiesforsold',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertiesforsold',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertiesforsold',
            name='image',
            field=models.ImageField(default='defeult.jpg', upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='propertiesforsold',
            name='label',
            field=models.CharField(choices=[('A', 'Active'), ('R', 'Rent')], default='SOME STRING', max_length=2),
        ),
        migrations.AddField(
            model_name='propertiesforsold',
            name='picture_count',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertiesforsold',
            name='price',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertiesforsold',
            name='rooms',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertiesforsold',
            name='slug',
            field=models.SlugField(default='property-1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertiesforsold',
            name='title',
            field=models.CharField(default='Demo property 1', max_length=100),
            preserve_default=False,
        ),
    ]
