# Generated by Django 3.1.1 on 2021-03-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0008_item_have_parking'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='have_balcony',
            field=models.BooleanField(default=False, verbose_name='balcony'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_diningRoom',
            field=models.BooleanField(default=False, verbose_name='diningRoom'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_drinage',
            field=models.BooleanField(default=False, verbose_name='drinage'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_electricityBackup',
            field=models.BooleanField(default=False, verbose_name='electricityBackup'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_electricityPole',
            field=models.BooleanField(default=False, verbose_name='electricityPole'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_elevator',
            field=models.BooleanField(default=False, verbose_name='elevator'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_garden',
            field=models.BooleanField(default=False, verbose_name='garden'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_hallRoom',
            field=models.BooleanField(default=False, verbose_name='hallRoom'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_kidsPlayground',
            field=models.BooleanField(default=False, verbose_name='kidsPlayground'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_lift',
            field=models.BooleanField(default=False, verbose_name='lift'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_road',
            field=models.BooleanField(default=False, verbose_name='road'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_securityStaff',
            field=models.BooleanField(default=False, verbose_name='securityStaff'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_water',
            field=models.BooleanField(default=False, verbose_name='water'),
        ),
        migrations.AddField(
            model_name='item',
            name='have_waterSupply',
            field=models.BooleanField(default=False, verbose_name='waterSupply'),
        ),
    ]
