# Generated by Django 3.1.1 on 2021-04-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0009_item_area_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='built_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
