# Generated by Django 3.1.1 on 2020-10-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0009_auto_20201008_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertiesforrent',
            name='user',
        ),
        migrations.DeleteModel(
            name='PropertiesForSold',
        ),
        migrations.DeleteModel(
            name='PropertiesForRent',
        ),
    ]
