# Generated by Django 3.1.1 on 2021-01-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0010_auto_20201022_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('K', 'Kathmandu'), ('L', 'Lalitpur'), ('L', 'Bhaktapur'), ('L', 'Chitwan')], default='SOME STRING', max_length=2),
        ),
    ]
