# Generated by Django 3.1.1 on 2021-04-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0010_item_built_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Latitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='Longitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
