# Generated by Django 3.1.1 on 2021-01-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0011_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Description',
            field=models.CharField(default='Property details', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='map',
            field=models.CharField(default='Google map', max_length=150),
            preserve_default=False,
        ),
    ]
