# Generated by Django 3.1.1 on 2021-04-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0011_auto_20210402_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Latitude',
            field=models.CharField(default='85.30152361628183', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='Longitude',
            field=models.CharField(default='27.69249498202916', max_length=10),
            preserve_default=False,
        ),
    ]
