# Generated by Django 3.1.1 on 2021-01-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0012_auto_20210101_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('H', 'House'), ('A', 'Apartment'), ('L', 'Land')], default='Error fetching category', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('A', 'Active'), ('R', 'Rent')], default='Active', max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('K', 'Kathmandu'), ('L', 'Lalitpur'), ('L', 'Bhaktapur'), ('C', 'Chitwan')], default='Kathmandu', max_length=2),
        ),
    ]
