# Generated by Django 3.1.1 on 2021-04-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0012_auto_20210402_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Latitude',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='item',
            name='Longitude',
            field=models.CharField(max_length=25),
        ),
    ]
