# Generated by Django 3.1.1 on 2021-04-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0013_auto_20210404_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='AP_have_electricity',
            field=models.BooleanField(default=False, verbose_name='Ap_electricity'),
        ),
        migrations.AddField(
            model_name='item',
            name='Ap_have_dining_room',
            field=models.BooleanField(default=False, verbose_name='Ap_dining_room'),
        ),
        migrations.AddField(
            model_name='item',
            name='Ap_have_drinage',
            field=models.BooleanField(default=False, verbose_name='Ap_drinage'),
        ),
        migrations.AddField(
            model_name='item',
            name='Ap_have_kids_playground',
            field=models.BooleanField(default=False, verbose_name='Ap_kids_playground'),
        ),
        migrations.AddField(
            model_name='item',
            name='Ap_have_lift',
            field=models.BooleanField(default=False, verbose_name='Ap_lift'),
        ),
        migrations.AddField(
            model_name='item',
            name='Ap_have_parking',
            field=models.BooleanField(default=False, verbose_name='Ap_Parking'),
        ),
        migrations.AddField(
            model_name='item',
            name='Ap_have_water_supply',
            field=models.BooleanField(default=False, verbose_name='Ap_water_supply'),
        ),
        migrations.AddField(
            model_name='item',
            name='La_have_drinage',
            field=models.BooleanField(default=False, verbose_name='La_drinage'),
        ),
        migrations.AddField(
            model_name='item',
            name='La_have_electricity',
            field=models.BooleanField(default=False, verbose_name='La_electricity'),
        ),
        migrations.AddField(
            model_name='item',
            name='La_have_road',
            field=models.BooleanField(default=False, verbose_name='La_road'),
        ),
        migrations.AddField(
            model_name='item',
            name='La_have_water',
            field=models.BooleanField(default=False, verbose_name='La_water'),
        ),
    ]
