# Generated by Django 3.1.1 on 2021-04-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0014_auto_20210406_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='map',
        ),
        migrations.AlterField(
            model_name='item',
            name='Latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='Longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='area_face',
            field=models.CharField(blank=True, choices=[('E', 'East'), ('W', 'West'), ('N', 'North'), ('S', 'South')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('H', 'House'), ('A', 'Apartment'), ('L', 'Land')], max_length=2, null=True),
        ),
    ]
