# Generated by Django 3.1.1 on 2021-01-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0014_auto_20210103_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
