# Generated by Django 3.1.1 on 2021-01-15 19:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0014_auto_20210115_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
