# Generated by Django 3.1.1 on 2021-01-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0015_auto_20210115_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
    ]
