# Generated by Django 3.1.1 on 2021-01-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0015_auto_20210103_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='property_id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
