# Generated by Django 3.1 on 2021-05-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0015_auto_20210406_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='images',
            new_name='image',
        ),
    ]
