# Generated by Django 3.1.1 on 2021-01-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0016_auto_20210113_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='property_id',
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
