# Generated by Django 3.1 on 2021-05-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0017_auto_20210504_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imageitem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jaggasale.item'),
        ),
    ]
