# Generated by Django 3.1.1 on 2021-02-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0017_auto_20210205_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='map',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
