# Generated by Django 3.1.1 on 2021-02-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0018_auto_20210208_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sold_or_rent',
            field=models.CharField(choices=[('sold', 'SOLD'), ('rent', 'RENT')], default='SOLD', max_length=4),
        ),
    ]
