# Generated by Django 3.1 on 2021-05-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0019_auto_20210507_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='imageitem',
            new_name='item',
        ),
    ]
