# Generated by Django 3.1.1 on 2021-03-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0019_item_sold_or_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
