# Generated by Django 3.1 on 2021-05-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0020_auto_20210508_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='title',
        ),
    ]
