# Generated by Django 3.1 on 2021-05-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0021_remove_images_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='ItemImages',
        ),
    ]
