# Generated by Django 3.1 on 2021-05-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jaggasale', '0024_auto_20210509_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
