# Generated by Django 3.1.1 on 2021-03-19 14:58

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Company History', max_length=30)),
                ('history_main_img', models.ImageField(default='default.jpg', upload_to='static/images')),
                ('company_history_top_section', ckeditor_uploader.fields.RichTextUploadingField(default='First paragraph here')),
                ('company_history_middle_section', ckeditor_uploader.fields.RichTextUploadingField(default='Second paragraph here')),
                ('company_history_buttom_section', ckeditor_uploader.fields.RichTextUploadingField(default='Third paragraph here')),
                ('office_location_headquarter_title', models.CharField(default='Headquarter', max_length=30)),
                ('office_location_headquarter_info', ckeditor_uploader.fields.RichTextUploadingField(default='This branch info here')),
                ('office_location_branch_1_title', models.CharField(default='Lalitpur office', max_length=30)),
                ('office_location_branch_1_info', ckeditor_uploader.fields.RichTextUploadingField(default='This branch info here')),
                ('office_location_branch_2_title', models.CharField(default='Bhaktapur office', max_length=30)),
                ('office_location_branch_2_info', ckeditor_uploader.fields.RichTextUploadingField(default='This branch info here')),
                ('facebook_page', models.CharField(default='#', max_length=50)),
                ('twitter_page', models.CharField(default='#', max_length=50)),
                ('google_page', models.CharField(default='#', max_length=50)),
                ('youtube_page', models.CharField(default='#', max_length=50)),
                ('linkedin_page', models.CharField(default='#', max_length=50)),
                ('instagram_page', models.CharField(default='#', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+977 9845900495', max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9779812345678'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(default='Thesadishgautam@gmail.com', max_length=70)),
                ('location', models.CharField(default='Tinkune, KTM', max_length=100)),
                ('office_days', models.CharField(default='Monday – Friday', max_length=100)),
                ('office_time', models.CharField(default='10:00AM – 6:00PM', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Our_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rich Wacksman', max_length=30)),
                ('position', models.CharField(default='Chief Legal Officer', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='static/images')),
                ('facebook', models.CharField(default='#', max_length=50)),
                ('twitter', models.CharField(default='#', max_length=50)),
                ('gmail', models.CharField(default='#', max_length=50)),
                ('linkedin', models.CharField(default='#', max_length=50)),
                ('instagram', models.CharField(default='#', max_length=50)),
                ('outlook', models.CharField(default='#', max_length=50)),
            ],
        ),
    ]
