# Generated by Django 3.1.1 on 2021-01-20 09:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_auto_20210116_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_history', ckeditor_uploader.fields.RichTextUploadingField()),
                ('name', models.CharField(default='Rich Wacksman', max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='static/images')),
            ],
        ),
    ]
