# Generated by Django 3.1.1 on 2021-01-20 15:03

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='facebook',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='gmail',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='instagram',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='linkedin',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='office_location_bhaktapur',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_us',
            name='office_location_headquarter',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='kathmandu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_us',
            name='office_location_lalitpur',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Lalitpur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_us',
            name='outlook',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='position',
            field=models.CharField(default='Chief Legal Officer', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='twitter',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
