# Generated by Django 3.1.1 on 2021-01-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_auto_20210120_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rich Wacksman', max_length=30)),
                ('position', models.CharField(default='Chief Legal Officer', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='static/images')),
                ('facebook', models.CharField(default='#', max_length=50)),
                ('twitter', models.CharField(default='#', max_length=50)),
                ('gmail', models.CharField(default='#', max_length=50)),
                ('linkedin', models.CharField(default='#', max_length=50)),
                ('instagram', models.CharField(default='#', max_length=50)),
                ('outlook', models.CharField(default='#', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='image',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='name',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='outlook',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='position',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='twitter',
        ),
        migrations.AddField(
            model_name='about_us',
            name='title',
            field=models.CharField(default='Company History', max_length=30),
        ),
    ]
