# Generated by Django 3.1.1 on 2021-01-21 16:58

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20210120_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_us',
            name='company_history',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='office_location_bhaktapur',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='office_location_headquarter',
        ),
        migrations.RemoveField(
            model_name='about_us',
            name='office_location_lalitpur',
        ),
        migrations.AddField(
            model_name='about_us',
            name='company_history_buttom_section',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Third paragraph here'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='company_history_middle_section',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Second paragraph here'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='company_history_top_section',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='First paragraph here'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='facebook_page',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='google_page',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='instagram_page',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='linkedin_page',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='office_location_branch_1_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='This branch info here'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='office_location_branch_1_title',
            field=models.CharField(default='Lalitpur office', max_length=30),
        ),
        migrations.AddField(
            model_name='about_us',
            name='office_location_branch_2_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='This branch info here'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='office_location_branch_2_title',
            field=models.CharField(default='Bhaktapur office', max_length=30),
        ),
        migrations.AddField(
            model_name='about_us',
            name='office_location_headquarter_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='This branch info here'),
        ),
        migrations.AddField(
            model_name='about_us',
            name='office_location_headquarter_title',
            field=models.CharField(default='Headquarter', max_length=30),
        ),
        migrations.AddField(
            model_name='about_us',
            name='twitter_page',
            field=models.CharField(default='#', max_length=50),
        ),
        migrations.AddField(
            model_name='about_us',
            name='youtube_page',
            field=models.CharField(default='#', max_length=50),
        ),
    ]
