# Generated by Django 3.1.1 on 2021-01-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_auto_20210121_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='history_main_img',
            field=models.ImageField(default='default.jpg', upload_to='static/images'),
        ),
    ]
